### ISSUE TITLE
How pseudo labels works?

### ISSUE THREAD

**Issue by afoxxvi** [mrsempress/OBMO#1]
Hi, Huang.
I have a question about the pseudo label.
For example, if the original dataset is each image corresponding to one gt label file containing 5 objects, after applying OBMO module, what does the new dataset looks like? each image corresponding to a label file containing 5x5 objects(5x1 gt, 5x4 pseudo) with scores, or transformed to 5 images, each of them corresponding to one label file containing 5 objects, one containing gt label while the remaining 4 containing pseudo labels.
Thank you.

**Comment by mrsempress** [comment]
The former: each image corresponds to a label file containing 5x5 objects(5x1 gt, 5x4 pseudo) with scores.
